USE [FINANCEIRO]
GO

/****** Object:  Table [dbo].[TB_HISTORICO_FINANC]    Script Date: 08/02/2025 15:37:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_HISTORICO_FINANC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDREGISTRO] [int] NULL,
	[DT_GASTO] [date] NULL,
	[VL_TOTAL] [decimal](10, 2) NULL,
	[VL_PARCELA] [decimal](10, 2) NULL,
	[QT_PARCELA] [int] NULL,
	[N_PARCELA] [int] NULL,
	[MES_DEBITO_PARCELA] [int] NULL,
	[ANO_DEBITO_PARCELA] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


