USE [FINANCEIRO]
GO

/****** Object:  Table [dbo].[TB_MENSAGENS_COLETADAS]    Script Date: 28/01/2025 11:46:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_MENSAGENS_COLETADAS](
	[ID_COLETA] [int] NOT NULL,
	[DATA_COLETA] [date] NULL,
	[DATA_GASTO] [date] NULL,
	[DESCRICAO] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_COLETA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


